### ISSUE TITLE
Scala 3 only: `java.lang.NoSuchMethodError: ...TLSProtocol$SessionBytes$.unapply(...)`

### ISSUE THREAD

**Issue by mkurz** [apache/incubator-pekko-http#183]
[This scripted test](https://github.com/playframework/playframework/tree/main/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http-http2), migrated to pekko in https://github.com/playframework/playframework/pull/11847

* Works fine with Scala 2.13 :heavy_check_mark: 
* Fails with Scala 3 :x: 

Seems like this has to do with how `unapply` methods changed in Scala 3 (?)
* https://docs.scala-lang.org/scala3/guides/migration/incompat-other-changes.html#explicit-call-to-unapply
* https://docs.scala-lang.org/scala3/reference/changed-features/pattern-matching.html

Snapshot used:
* pekko-http: `0.0.0+4411-6fe04045-SNAPSHOT`
* pekko: `0.0.0+26669-ec5b6764-SNAPSHOT`

```
[error] Uncaught error from thread [application-pekko.actor.default-dispatcher-4]: 'org.apache.pekko.stream.TLSProtocol$SessionBytes org.apache.pekko.stream.TLSProtocol$SessionBytes$.unapply(org.apache.pekko.stream.TLSProtocol$SessionBytes)', shutting down JVM since 'pekko.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
[error] java.lang.NoSuchMethodError: 'org.apache.pekko.stream.TLSProtocol$SessionBytes org.apache.pekko.stream.TLSProtocol$SessionBytes$.unapply(org.apache.pekko.stream.TLSProtocol$SessionBytes)'
[error]         at org.apache.pekko.http.impl.engine.http2.ProtocolSwitch$$anon$1$$anon$2.onPush(ProtocolSwitch.scala:65)
[error]         at org.apache.pekko.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:555)
[error]         at org.apache.pekko.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:433)
[error]         at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:662)
[error]         at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:532)
[error]         at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:637)
[error]         at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.org$apache$pekko$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:813)
[error]         at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:831)
[error]         at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
[error]         at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
[error]         at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:729)
[error]         at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
[error]         at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
[error]         at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
[error]         at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
[error]         at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
````

Line triggering the exception:
https://github.com/apache/incubator-pekko-http/blob/0dc1da23cc465d8795f33daa513298afc2841ab5/http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/ProtocolSwitch.scala#L65

[`SessionBytes`](https://github.com/apache/incubator-pekko/blob/bed33cd4f00613f033638928904a29b8ce79071a/stream/src/main/scala/org/apache/pekko/stream/SslTlsOptions.scala#L182-L184):

```scala
  final case class SessionBytes(session: SSLSession, bytes: ByteString)
      extends SslTlsInbound
      with scaladsl.ScalaSessionAPI
```

`scaladsl.ScalaSessionAPI`:
https://github.com/apache/incubator-pekko/blob/main/stream/src/main/scala/org/apache/pekko/stream/scaladsl/TLS.scala#L249-L294

~In case it's needed, if you want to run the scripted tests yourself let me know, so I can give instructions.~ see comment below

**Comment by mkurz** [comment]
BTW: Tested with Scala 3.3.0 and 3.3.1-RC1

**Comment by mkurz** [comment]
If you want to reproduce locally:
```
git clone git@github.com:mkurz/playframework.git
git checkout pekko
```
```
sbt
project Sbt-Plugin;
set scriptedSbt := "1.9.0"; set scriptedLaunchOpts += "-Dscala.version=3.3.1-RC1"; set scriptedLaunchOpts += "-Dscala.crossversions=3.3.1-RC1";
scripted play-sbt-plugin/http-backend-pekko-http-http2
```

if you try with scala versions set to 2.13.11 the test will pass.

**Comment by pjfanning** [comment]
#184 might be a pragmatic change to get around this

we should try to produce a minimized case test case to present to the Dotty team

**Comment by pjfanning** [comment]
@mkurz could you try Pekko HTTP version 0.0.0+4434-6ab07a99-SNAPSHOT ?

**Comment by bishabosha** [comment]
did you make an issue with https://github.com/lampepfl/dotty?

**Comment by pjfanning** [comment]
@bishabosha So far the only reproducible case requires using a sbt scripted test that uses a large number of libraries.

I tried to produce a minimized case in scastie but had no luck reproducing anything like the behaviour that @mkurz is reporting.

**Comment by jrudolph** [comment]
This sounds like a binary incompatibility between the pekko version pekko-http is built against versus the pekko version you run with. It sounds like pekko-http 4411 and pekko 26669 should be compatible but maybe versions were evicted somewhere? In any case, there is no binary compatibility guarantee between SNAPSHOT versions right now (especially since Scala 3 versions have been bumped multiple times in recent months).

We probably do not have to do anything here other than specifying which version are supposed to work together (which will be easier once there are proper non-snapshots versions out there). Later when releases are out, mima should find these binary incompatibilities.

**Comment by jrudolph** [comment]
I tried the reproducer and it seems the project has the scala 3 artifacts of pekko-http on the classpath but the scala 2.13 artifacts of pekko core modules. So, this seems to be a problem with the setup in Play.

**Comment by jrudolph** [comment]
```
[info] org.apache.pekko:pekko-actor-typed_2.13:0.0.0+26669-ec5b6764-SNAPSHOT
[info] org.apache.pekko:pekko-actor_2.13:0.0.0+26669-ec5b6764-SNAPSHOT
[info] org.apache.pekko:pekko-http-core_3:0.0.0+4411-6fe04045-SNAPSHOT
[info] org.apache.pekko:pekko-parsing_3:0.0.0+4411-6fe04045-SNAPSHOT
[info] org.apache.pekko:pekko-protobuf-v3_2.13:0.0.0+26669-ec5b6764-SNAPSHOT
[info] org.apache.pekko:pekko-serialization-jackson_2.13:0.0.0+26669-ec5b6764-SNAPSHOT
[info] org.apache.pekko:pekko-slf4j_2.13:0.0.0+26669-ec5b6764-SNAPSHOT
[info] org.apache.pekko:pekko-stream_2.13:0.0.0+26669-ec5b6764-SNAPSHOT
```

**Comment by jrudolph** [comment]
Maybe this needs to be updated, @mkurz?

https://github.com/mkurz/playframework/blob/4ce5ee2a19a5502a7add6b9b6755fac6eefb47e9/dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala#L130

**Comment by jrudolph** [comment]
It works when commenting out https://github.com/mkurz/playframework/blob/4ce5ee2a19a5502a7add6b9b6755fac6eefb47e9/dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala#L122-L133

**Comment by mkurz** [comment]
sorry for the delay, I will check the scripted test again tomorrow or over the weekend and also apply @jrudolph code change (I probably overlooked that line)

**Comment by mkurz** [comment]
What are the latest pekko / pekko-http versions to use?
https://github.com/apache/incubator-pekko/releases/tag/v1.0.0-RC3 does not seem to be hosted on maven central (that's what I expected because it's a non-snapshot release, but maybe I am wrong)
Also https://github.com/apache/incubator-pekko-http/tags does not have any RCs so far.
Thanks!

**Comment by pjfanning** [comment]
@mkurz the RCs are internal candidates that need to be voted on by ASF members. They are in the staging area of the ASF Nexus repo (repository.apache.org).

Best to stick with snapshots if you are already testing with those.

https://cwiki.apache.org/confluence/display/PEKKO/Testing+with+Pekko+Snapshot+Jars

**Comment by mkurz** [comment]
So yes, this was a problem in Play's setup. All the tests are passing now when reverting https://github.com/playframework/playframework/commit/78c5bfdb885fab3d82938ddbc38f73c094a6d7ed.
That commit was introduced in
* https://github.com/playframework/playframework/pull/11738

as kind of a hack to work around the problem that akka-http 10.2.x does not have Scala 3 artifacts published, so we make use of the for3use2 switch there.
Seems I just forgot to remove that workaround when testing pekko...

Sorry for all the noise and thanks!

**Comment by jrudolph** [comment]
Great and good to know it works now :)
